# Generated by Django 4.2.4 on 2023-11-01 23:43

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Equipe')),
                ('abreviacao', models.CharField(max_length=200, verbose_name='Sigla/Abreviação da Equipe')),
                ('fundacao', models.DateField(blank=True, null=True, verbose_name='Fundado em')),
                ('estado', models.CharField(max_length=200, verbose_name='Estado da equipe')),
                ('pais', models.CharField(max_length=2, verbose_name='País da equipe')),
                ('escudo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Escudo')),
                ('tecnico', models.CharField(max_length=200, verbose_name='Técnico da Equipe')),
                ('cor_primaria', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('cor_secundaria', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Torneio')),
                ('data', models.DateField(blank=True, verbose_name='Data do Torneio')),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início da Partida')),
                ('data_final', models.DateTimeField(verbose_name='Data de Término da Partida')),
                ('estadio', models.CharField(help_text='Estádio em que o jogo ocorreu', max_length=200, verbose_name='Estádio')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_casa', to='core.time', verbose_name='Time da Casa')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_visitante', to='core.time', verbose_name='Time Visitante')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneio_jogo', to='core.torneio', verbose_name='Torneio')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Jogador')),
                ('idade', models.IntegerField(blank=True, verbose_name='Idade')),
                ('nacionalidade', models.CharField(max_length=200, verbose_name='Nacionalidade')),
                ('dt_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('posicao', models.SmallIntegerField(choices=[(0, 'Goleiro'), (1, 'Zagueiro'), (2, 'Lateral'), (3, 'Volante'), (4, 'Meia'), (5, 'Atacante')], verbose_name='Posição do Jogador')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('preferencia_pe', models.SmallIntegerField(choices=[(0, 'Esquerdo'), (1, 'Direito')], verbose_name='Preferência de pé')),
                ('numero_camisa', models.IntegerField(blank=True, null=True, verbose_name='Número da Camisa')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_jogador', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateTimeField(verbose_name='Tempo em que registrou')),
                ('foi_contra', models.BooleanField(verbose_name='Contra?')),
                ('assistido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gol_jogador_assistido', to='core.jogador', verbose_name='Assistencia')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gol_jogador', to='core.jogador', verbose_name='Jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gol_jogo', to='core.jogo', verbose_name='Jogo')),
                ('time_marcou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gol_time_marcou', to='core.time', verbose_name='Time que Marcou')),
                ('time_sofreu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gol_time_sofreu', to='core.time', verbose_name='Time que Sofreu')),
            ],
            options={
                'verbose_name': 'Gol',
                'verbose_name_plural': 'Gols',
            },
        ),
        migrations.CreateModel(
            name='CompetidoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitorias', models.IntegerField(default=0, verbose_name='Vitorias')),
                ('derrotas', models.IntegerField(default=0, verbose_name='Derrotas')),
                ('empates', models.IntegerField(default=0, verbose_name='Empates')),
                ('gols_marcados', models.IntegerField(default=0, verbose_name='Gols Marcados')),
                ('gols_sofridos', models.IntegerField(default=0, verbose_name='Gols Sofridos')),
                ('cartao_amarelo', models.IntegerField(default=0, verbose_name='Cartão Amarelo')),
                ('cartao_vermelho', models.IntegerField(default=0, verbose_name='Cartão Vermelho')),
                ('saldo_gols', models.IntegerField(default=0, verbose_name='Saldo de Gols')),
                ('pontuacao', models.IntegerField(default=0, verbose_name='Pontuação')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competido_time', to='core.time', verbose_name='Time')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competido_torneio', to='core.torneio', verbose_name='Torneio')),
            ],
            options={
                'verbose_name': 'Competido por',
                'verbose_name_plural': 'Competidos por',
            },
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateTimeField(verbose_name='Tempo em que registrou')),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Amarelo'), (1, 'Vermelho')], verbose_name='Tipo de Cartão')),
                ('jogador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador_cartao', to='core.jogador', verbose_name='Jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartao_jogo', to='core.jogo', verbose_name='Jogo')),
                ('time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='time_cartao', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Cartão',
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
