# Generated by Django 4.2.4 on 2023-10-19 00:45

import core.constants
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Equipe')),
                ('abreviacao', models.CharField(max_length=200, verbose_name='Sigla/Abreviação da Equipe')),
                ('fundacao', models.DateField(blank=True, null=True, verbose_name='Fundado em')),
                ('cidade', models.CharField(max_length=200, verbose_name='Cidade sede da equipe')),
                ('escudo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL do Escudo')),
                ('escudo', models.FileField(blank=True, null=True, upload_to='cliente', verbose_name='Escudo')),
                ('anexado_em', models.DateField(blank=True, null=True, verbose_name='Anexado em')),
                ('tecnico', models.CharField(max_length=200, verbose_name='Técnico da Equipe')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Torneio')),
                ('ano', models.DateTimeField(blank=True, verbose_name='Ano do Torneio')),
            ],
            options={
                'verbose_name': 'Torneio',
                'verbose_name_plural': 'Torneios',
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateTimeField(blank=True, verbose_name='Data da Partida')),
                ('estadio', models.CharField(help_text='Estádio em que o jogo ocorreu', max_length=200, verbose_name='Estádio')),
                ('time_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_casa', to='core.time', verbose_name='Time da Casa')),
                ('time_visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_visitante', to='core.time', verbose_name='Time Visitante')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneio_jogo', to='core.time', verbose_name='Torneio')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Jogador')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('nacionalidade', models.CharField(max_length=200, verbose_name='Nacionalidade')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('posicao', models.SmallIntegerField(choices=[(0, 'Goleiro'), (1, 'Zagueiro'), (2, 'Lateral'), (3, 'Volante'), (4, 'Meia'), (5, 'Atacante')], verbose_name='Posição do Jogador')),
                ('peso', models.FloatField(verbose_name='Peso')),
                ('altura', models.FloatField(verbose_name='Altura')),
                ('preferencia_pe', models.SmallIntegerField(choices=[(0, 'Esquerdo'), (1, 'Direito')], verbose_name='Preferência de pé')),
                ('numero_camisa', models.IntegerField(blank=True, null=True, verbose_name='Número da Camisa')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_jogador', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='GolTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateTimeField(verbose_name='Tempo em que registrou')),
                ('contra', models.BooleanField(verbose_name='Foi Contra?')),
                ('marcado', models.BooleanField(verbose_name='Marcado?')),
                ('sofrido', models.BooleanField(verbose_name='Sofrido?')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gol_time', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Gol do Time',
                'verbose_name_plural': 'Gols do Time',
            },
        ),
        migrations.CreateModel(
            name='GolJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateTimeField(verbose_name='Tempo em que registrou')),
                ('contra', models.BooleanField(verbose_name='Foi Contra?')),
                ('marcado', models.BooleanField(verbose_name='Marcado?')),
                ('assistido', models.BooleanField(verbose_name='Assistido?')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gol_jogador', to='core.jogador', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Gol do Jogador',
                'verbose_name_plural': 'Gols do Jogador',
            },
        ),
        migrations.CreateModel(
            name='CompetidoPor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vitorias', models.IntegerField(verbose_name='Vitorias')),
                ('derrotas', models.IntegerField(verbose_name='Derrotas')),
                ('empates', models.IntegerField(verbose_name='Empates')),
                ('gols_marcados', models.IntegerField(verbose_name='Gols Marcados')),
                ('gols_sofridos', models.IntegerField(verbose_name='Gols Sofridos')),
                ('cartao_vermelho', models.IntegerField(verbose_name='Cartão Vermelho')),
                ('cartao_amarelo', models.IntegerField(verbose_name='Cartão Amarelo')),
                ('saldo_gols', models.IntegerField(verbose_name='Saldo de Gols')),
                ('pontuacao', models.IntegerField(verbose_name='Pontuação')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competido_time', to='core.time', verbose_name='Time')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competido_torneio', to='core.torneio', verbose_name='Torneio')),
            ],
            options={
                'verbose_name': 'Competido por',
                'verbose_name_plural': 'Competidos por',
            },
        ),
        migrations.CreateModel(
            name='CartaoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateTimeField(verbose_name='Tempo em que registrou')),
                ('tipo', models.SmallIntegerField(choices=[(core.constants.EnumCartao['AMARELO'], 'Amarelo'), (core.constants.EnumCartao['VERMELHO'], 'Vermelho')], verbose_name='Tipo de Cartão')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo_cartao_time', to='core.jogo', verbose_name='Jogo')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_cartao', to='core.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Cartão do Time',
                'verbose_name_plural': 'Cartões do Time',
            },
        ),
        migrations.CreateModel(
            name='CartaoJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateTimeField(verbose_name='Tempo em que registrou')),
                ('tipo', models.SmallIntegerField(choices=[(core.constants.EnumCartao['AMARELO'], 'Amarelo'), (core.constants.EnumCartao['VERMELHO'], 'Vermelho')], verbose_name='Tipo de Cartão')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_jogador_cartao', to='core.jogador', verbose_name='Time')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo_cartao_jogador', to='core.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Cartão do Jogador',
                'verbose_name_plural': 'Cartões do Jogador',
            },
        ),
    ]
