# Generated by Django 4.2.4 on 2023-11-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competidopor',
            name='torneio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competido_torneio', to='core.torneio', verbose_name='Torneio'),
        ),
    ]
