# Generated by Django 4.2.4 on 2023-09-11 23:22

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='altura',
            field=models.FloatField(verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='avaliacao_desempenho',
            field=models.SmallIntegerField(blank=True, choices=[(core.constants.EnumDesempenho['EXCELENTE'], 'Excelente'), (core.constants.EnumDesempenho['BOM'], 'Bom'), (core.constants.EnumDesempenho['MEDIO'], 'Médio'), (core.constants.EnumDesempenho['EM_DESENVOLVIMENTO'], 'Em desenvolvimento'), (core.constants.EnumDesempenho['PESSIMO'], 'Péssimo')], null=True, verbose_name='Avaliação de Desempenho'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='peso',
            field=models.FloatField(verbose_name='Peso'),
        ),
    ]
