# Generated by Django 4.2.4 on 2023-09-01 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='calendario',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='equipe_casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_casa', to='core.time', verbose_name='Equipe da Casa'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='equipe_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_visitante', to='core.time', verbose_name='Equipe Visitante'),
        ),
        migrations.DeleteModel(
            name='Equipe',
        ),
    ]
