# Generated by Django 4.2.4 on 2023-11-24 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_competidopor_torneio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jogo',
            old_name='data_inicio',
            new_name='data_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='jogador',
            name='nacionalidade',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='data_final',
        ),
        migrations.RemoveField(
            model_name='time',
            name='estado',
        ),
        migrations.AddField(
            model_name='jogador',
            name='apelido',
            field=models.CharField(default=1, max_length=200, verbose_name='Apelido do Jogador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='imagem',
            field=models.FileField(default=1, upload_to='', verbose_name='Imagem do Jogador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogador',
            name='pais',
            field=models.CharField(default=1, max_length=2, verbose_name='País'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='acabou',
            field=models.BooleanField(default=False, verbose_name='O Jogo Acabou?'),
        ),
        migrations.AlterField(
            model_name='competidopor',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competido_torneio', to='core.torneio', verbose_name='Torneio'),
        ),
        migrations.AlterField(
            model_name='time',
            name='abreviacao',
            field=models.CharField(max_length=3, verbose_name='Sigla/Abreviação da Equipe'),
        ),
    ]
