# Generated by Django 4.2.4 on 2023-10-27 11:19

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jogador_dt_nascimento_alter_jogador_idade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.DateTimeField(verbose_name='Tempo em que registrou')),
                ('tipo', models.SmallIntegerField(choices=[(0, 'Amarelo'), (1, 'Vermelho')], verbose_name='Tipo de Cartão')),
                ('jogador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogador_cartao', to='core.jogador', verbose_name='Jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogo_cartao_time', to='core.jogo', verbose_name='Jogo')),
            ],
            options={
                'verbose_name': 'Cartão do Time',
                'verbose_name_plural': 'Cartões do Time',
            },
        ),
        migrations.RemoveField(
            model_name='cartaotime',
            name='jogo',
        ),
        migrations.RemoveField(
            model_name='cartaotime',
            name='time',
        ),
        migrations.RemoveField(
            model_name='competidopor',
            name='cartao_amarelo',
        ),
        migrations.RemoveField(
            model_name='competidopor',
            name='cartao_vermelho',
        ),
        migrations.AddField(
            model_name='time',
            name='primeira_cor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='time',
            name='segunda_cor',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='torneio',
            name='ano',
            field=models.DateField(blank=True, verbose_name='Ano do Torneio'),
        ),
        migrations.DeleteModel(
            name='CartaoJogador',
        ),
        migrations.DeleteModel(
            name='CartaoTime',
        ),
        migrations.AddField(
            model_name='cartao',
            name='time',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_cartao', to='core.time', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='competidopor',
            name='cartao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cartao', to='core.cartao', verbose_name='Cartao'),
            preserve_default=False,
        ),
    ]
