# Generated by Django 4.2.4 on 2023-12-02 14:30

import core.models.cartao
import core.models.gol
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cartao_tempo_alter_gol_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='tempo_acrescimo',
            field=models.CharField(default=1231, max_length=6, validators=[core.models.cartao.validate_custom_time_format], verbose_name='Tempo de acrescimo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gol',
            name='tempo_acrescimo',
            field=models.CharField(default=1232, max_length=6, validators=[core.models.gol.validate_custom_time_format], verbose_name='Tempo de acrescimo'),
            preserve_default=False,
        ),
    ]
