# Generated by Django 4.2.4 on 2023-12-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cartao_tempo_acrescimo_gol_tempo_acrescimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='escudo_url',
            new_name='imagem',
        ),
    ]
