# Generated by Django 4.2.4 on 2023-12-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_escudo_url_time_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='imagem',
            field=models.URLField(verbose_name='Imagem do Jogador'),
        ),
    ]
