# Generated by Django 4.2.4 on 2023-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_jogador_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem do Jogador'),
        ),
    ]
