# Generated by Django 4.2.4 on 2023-12-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_jogador_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_jogador', to='core.time', verbose_name='Time'),
        ),
    ]
